import type { ReactNode } from 'react';

export interface BasecampBuild { id: string; title: string; author_name: string; how_it_works: string; models_used: string; rating_count: string; avg_rating: string }
export interface BasecampHomeProps { episode: { theme: string; brief?: string; status: string } | null; builds: BasecampBuild[]; counts?: { builds: number; builders: number; episodes: number }; countdown?: ReactNode; live?: boolean; origin?: string }

/** Shared, data-driven presentation. Production supplies PostgreSQL records. */
export function BasecampHome({episode,builds,counts,countdown,live=false,origin=''}:BasecampHomeProps){
 const href=(path:string)=>origin+path;
 return <div className="bc-page">
  <div className="bc-intro"><div><span className="bc-eyebrow">A LITTLE CURIOSITY GOES A LONG WAY.</span><h1>Welcome to basecamp.</h1><p>A place to build with AI, learn out loud, and find your people.</p></div><a className="bc-date" href={href('/season')}>Season 02 / The next chapter</a></div>
  <section className="bc-hero"><div className="bc-hero-copy"><span className="bc-badge">{live?'LIVE CHALLENGE':episode?.status==='complete'?'LATEST CHALLENGE':'THE NEXT CHALLENGE'}</span><h2>{episode?.theme||'Your next idea starts here.'}</h2><p>{episode?.brief||'Thirty minutes to turn a little curiosity into something real. Build it, share it, and learn together.'}</p><div className="bc-actions"><a className="bc-button" href={href('/submit')}>Share your build ↗</a><a className="bc-button bc-secondary" href={href('/challenge')}>Read the brief</a></div></div><div className="bc-hero-side"><span className="bc-eyebrow">THE BUILD WINDOW</span><strong>30 min</strong><p>A little time.<br/>A lot of possibility.</p><hr/>{countdown||<a href={href('/challenge')}>See challenge schedule →</a>}</div></section>
  {counts?<section className="bc-stats" aria-label="Community statistics">{[[counts.builds,'Builds on the workbench'],[counts.builders,'Builders around the fire'],[counts.episodes,'Challenges and counting']].map(([n,label])=><div className="bc-stat" key={label}><strong>{Number(n).toLocaleString()}</strong><span>{label}</span></div>)}</section>:<div className="bc-trail"><a href={href('/signup')}>01 / Join the camp ↗</a><a href={href('/builds')}>02 / Explore the workbench ↗</a><a href={href('/vote')}>03 / Encourage a builder ↗</a></div>}
  <div className="bc-section-head"><div><h2>Fresh off the workbench</h2><p>Small experiments. Big possibilities. Take a look around.</p></div><a href={href('/builds')}>Explore all builds →</a></div>
  {builds.length>0?<div className="bc-builds">{builds.map((b,i)=><a className="bc-build" key={b.id} href={href(`/builds/${encodeURIComponent(b.id)}`)}><div className={`bc-build-art bc-art-${i%3}`}><span>{b.title}</span></div><div className="bc-build-body"><div className="bc-build-title"><h3>{b.title}</h3><span>{b.models_used}</span></div><p>{b.how_it_works}</p><div className="bc-build-meta"><span>by {b.author_name}</span><span>{Number(b.rating_count)>0?`${Number(b.avg_rating).toFixed(1)} / 5 · ${b.rating_count} raters`:'Be the first to rate ↗'}</span></div></div></a>)}</div>:<div className="bc-empty"><h3>There’s room for your next idea.</h3><p>Explore the community’s work and find your next spark.</p><a className="bc-button" href={href('/builds')}>Visit the workbench ↗</a></div>}
  <section className="bc-banner"><div><span className="bc-eyebrow">SAME COMMUNITY. A NEW CLEARING.</span><h3>Your history belongs here, too.</h3><p>Your account, builds, ratings, and profile stay with you. Just settle in.</p></div><a className="bc-button bc-secondary" href={href('/how-it-works')}>Find your way around →</a></section>
 </div>
}
